import { F } from "./base";

export const siteTables = [
  {
    name: "alif_site_content",
    label: "Site Content",
    orderBy: "section",
    listBy: (r) => `${r.section} · v${r.version ?? 1}`,
    fields: [
      F("section", "Section", "sitesection"),
      F("data", "Content", "sitecontent"),
      F("is_published", "Published", "bool"),
    ],
  },
  {
    name: "alif_projects",
    label: "Projects",
    orderBy: "sort_order",
    listBy: (r) => `${r.sort_order ?? 0} · ${r.title}`,
    fields: [
      F("title", "Title"),
      F("slug", "Slug", "text", { readOnly: true }),
      F("short_description", "Short description (card)", "textarea", { hint: "Wrap a word in **word** to bold it on the site." }),
      F("description", "Description", "textarea", { hint: "Wrap a word in **word** to bold it on the site." }),
      F("image", "Image URL + Upload", "image"),
      F("github", "GitHub URL"),
      F("demo", "Demo URL"),
      F("featured", "Featured", "bool"),
      F("is_published", "Published", "bool"),
      F("show_github", "Show GitHub", "bool"),
      F("sort_order", "Sort order", "number"),
    ],
  },
  {
    name: "alif_project_details",
    label: "Project Details",
    orderBy: "slug",
    listBy: (r) => r.slug || r.title,
    fields: [
      F("project_id", "Project", "hidden"),
      F("title", "Title", "text", { readOnly: true }),
      F("slug", "Slug", "text", { readOnly: true }),
      F("description", "Short description", "textarea", { readOnly: true }),
      F("full_description", "Full description", "textarea", { hint: "Wrap a word in **word** to bold it on the site." }),
      F("github_url", "GitHub URL"),
      F("demo_url", "Demo URL"),
      F("thumbnail_url", "Thumbnail URL + Upload", "image"),
      F("status", "Status"),
      F("featured", "Featured", "bool"),
      F("technologies", "Technologies (select from Technology Icons)", "techselect"),
      F("features", "Features (numbered)", "listedit", { item: "feature" }),
      F("gallery", "Gallery (Title + Upload)", "galleryedit"),
      F("timeline", "Timeline (entry per phase)", "timelineedit"),
      F("challenges", "Challenges (numbered)", "listedit", { item: "challenge" }),
      F("solutions", "Solutions (numbered)", "listedit", { item: "solution" }),
      F("statistics", "Statistics (Label + Value)", "statsedit"),
      F("database_info", "Database info", "dbinfo"),
      F("show_database", "Show database", "bool"),
      F("show_github", "Show GitHub", "bool"),
      F("show_demo", "Show demo", "bool"),
    ],
  },
];
